env:
  DOCKER_USERNAME: fm12
  DOCKER_PASSWORD: ENCRYPTED[9171dc098e2ab6d394f7ed8a7ebe39e3bc82415981bb0b9836841be148742181bd2aca1b3fbfc99242a19c5c2e4e2e14]
  TAG: latest



base_docker_builder:
  build_script: docker pull mbsimenv/base:$TAG || true; docker build --cache-from mbsimenv/base:$TAG --tag mbsimenv/base:$TAG --build-arg=JOBS=2 docker/baseImage
  login_script: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  push_script: docker push mbsimenv/base:$TAG
  
build_docker_builder:
  depends_on: 
    - base
  build_script: docker pull mbsimenv/build:$TAG || true; docker build --cache-from mbsimenv/build:$TAG --tag mbsimenv/build:$TAG --build-arg=FROMTAG=$TAG --build-arg=JOBS=2 docker/buildImage
  login_script: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  push_script: docker push mbsimenv/build:$TAG
  
run_docker_builder:
  depends_on: 
    - build
  build_script: docker build --no-cache --tag mbsimenv/run:$TAG --build-arg=FROMTAG=$TAG --build-arg=JOBS=2 -f docker/runImage/Dockerfile docker/..
  login_script: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  push_script: docker push mbsimenv/run:$TAG
  
proxy_docker_builder:
  build_script: docker pull mbsimenv/proxy:$TAG || true; docker build --cache-from mbsimenv/proxy:$TAG --tag mbsimenv/proxy:$TAG docker/proxyImage
  login_script: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  push_script: docker push mbsimenv/proxy:$TAG
  
autobuild_docker_builder:
  depends_on: 
    - build
  build_script: docker pull mbsimenv/autobuild:$TAG || true; docker build --cache-from mbsimenv/autobuild:$TAG --build-arg=FROMTAG=$TAG --tag mbsimenv/autobuild:$TAG -f docker/autobuildImage/Dockerfile docker/..
  login_script: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  push_script: docker push mbsimenv/autobuild:$TAG
  
webserver_docker_builder:
  build_script: docker pull mbsimenv/webserver:$TAG || true; docker build --cache-from mbsimenv/webserver:$TAG --tag mbsimenv/webserver:$TAG -f docker/webserverImage/Dockerfile docker/.
  login_script: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  push_script: docker push mbsimenv/webserver:$TAG
  
webapp_docker_builder:
  build_script: docker pull mbsimenv/webapp:$TAG || true; docker build --cache-from mbsimenv/webapp:$TAG --tag mbsimenv/webapp:$TAG -f docker/webappImage/Dockerfile docker/.
  login_script: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  push_script: docker push mbsimenv/webapp:$TAG
  
webapprun_docker_builder:
  depends_on: 
    - autobuild
  build_script: docker pull mbsimenv/webapprun:$TAG || true; docker build --cache-from mbsimenv/webapprun:$TAG --build-arg=FROMTAG=$TAG --tag mbsimenv/webapprun:$TAG docker/webapprunImage
  login_script: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  push_script: docker push mbsimenv/webapprun:$TAG
