# Generated by Django 3.0.1 on 2020-05-29 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('buildType', models.CharField(max_length=50)),
                ('command', models.TextField()),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField(null=True)),
                ('fmatvecBranch', models.CharField(max_length=50)),
                ('hdf5serieBranch', models.CharField(max_length=50)),
                ('openmbvBranch', models.CharField(max_length=50)),
                ('mbsimBranch', models.CharField(max_length=50)),
                ('fmatvecUpdateOK', models.BooleanField(null=True)),
                ('hdf5serieUpdateOK', models.BooleanField(null=True)),
                ('openmbvUpdateOK', models.BooleanField(null=True)),
                ('mbsimUpdateOK', models.BooleanField(null=True)),
                ('fmatvecUpdateOutput', models.TextField()),
                ('hdf5serieUpdateOutput', models.TextField()),
                ('openmbvUpdateOutput', models.TextField()),
                ('mbsimUpdateOutput', models.TextField()),
                ('fmatvecUpdateTooltip', models.TextField()),
                ('hdf5serieUpdateTooltip', models.TextField()),
                ('openmbvUpdateTooltip', models.TextField()),
                ('mbsimUpdateTooltip', models.TextField()),
                ('fmatvecUpdateCommitID', models.CharField(max_length=50)),
                ('hdf5serieUpdateCommitID', models.CharField(max_length=50)),
                ('openmbvUpdateCommitID', models.CharField(max_length=50)),
                ('mbsimUpdateCommitID', models.CharField(max_length=50)),
                ('fmatvecUpdateMsg', models.CharField(max_length=100)),
                ('hdf5serieUpdateMsg', models.CharField(max_length=100)),
                ('openmbvUpdateMsg', models.CharField(max_length=100)),
                ('mbsimUpdateMsg', models.CharField(max_length=100)),
                ('distributionOK', models.BooleanField(null=True)),
                ('distributionOutput', models.TextField()),
                ('distributionFile', models.FileField(null=True, upload_to='')),
                ('distributionDebugFile', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('toolName', models.CharField(max_length=200)),
                ('willFail', models.BooleanField()),
                ('configureOK', models.BooleanField(null=True)),
                ('configureOutput', models.TextField(null=True)),
                ('makeOK', models.BooleanField(null=True)),
                ('makeOutput', models.TextField(null=True)),
                ('makeCheckOK', models.BooleanField(null=True)),
                ('makeCheckOutput', models.TextField(null=True)),
                ('docOK', models.BooleanField(null=True)),
                ('docOutput', models.TextField(null=True)),
                ('xmldocOK', models.BooleanField(null=True)),
                ('xmldocOutput', models.TextField(null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='builds.Run')),
            ],
        ),
    ]
