# Generated by Django 3.0.1 on 2020-07-07 20:00

from django.db import migrations

def nullempty(apps, schema_editor):
    Model = apps.get_model("builds", "Tool")
    fields = ["configureOutput", "makeOutput", "makeCheckOutput", "docOutput", "xmldocOutput"]
    for field in fields:
        filter_param = {"{}__isnull".format(field): True}
        update_param = {field: ""}
        Model.objects.filter(**filter_param).update(**update_param)

class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(nullempty, migrations.RunPython.noop)
    ]
