# Generated by Django 3.0.1 on 2020-07-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0002_nullempty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='distributionDebugFile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='run',
            name='distributionFile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='run',
            name='distributionOK',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='endTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='fmatvecUpdateOK',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='hdf5serieUpdateOK',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='mbsimUpdateOK',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='openmbvUpdateOK',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='configureOK',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='configureOutput',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tool',
            name='docOK',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='docOutput',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tool',
            name='makeCheckOK',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='makeCheckOutput',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tool',
            name='makeOK',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='makeOutput',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tool',
            name='xmldocOK',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='xmldocOutput',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
