# Generated by Django 3.0.1 on 2020-07-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0003_nullblank'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='toolsFailed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
