# Generated by Django 3.0.1 on 2022-02-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0004_filterfailed'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='executor',
            field=models.TextField(default='MBSim-Env'),
            preserve_default=False,
        ),
    ]
