# Generated by Django 3.0.1 on 2022-02-25 12:18

from django.db import migrations, models
import datetime

def tooltipToNameAndDate(apps, schema_editor):
  Run = apps.get_model('builds', 'Run')
  for run in Run.objects.all():
    for repo in ["fmatvec", "hdf5serie", "openmbv", "mbsim"]:
      tooltip=getattr(run, repo+"UpdateTooltip") # = "Commit: %H%nAuthor: %an%nDate:   %ad%n%s%n%b"
      line=tooltip.split("\n")
      setattr(run, repo+"UpdateAuthor", line[1][8:])
      setattr(run, repo+"UpdateDate", datetime.datetime.strptime(line[2][8:], "%a %b %d %H:%M:%S %Y %z"))
      run.save()

class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0005_run_executor'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='fmatvecUpdateAuthor',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='run',
            name='hdf5serieUpdateAuthor',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='run',
            name='openmbvUpdateAuthor',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='run',
            name='mbsimUpdateAuthor',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='run',
            name='fmatvecUpdateDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='hdf5serieUpdateDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='openmbvUpdateDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='mbsimUpdateDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(tooltipToNameAndDate),
        migrations.RemoveField(
            model_name='run',
            name='fmatvecUpdateTooltip',
        ),
        migrations.RemoveField(
            model_name='run',
            name='hdf5serieUpdateTooltip',
        ),
        migrations.RemoveField(
            model_name='run',
            name='mbsimUpdateTooltip',
        ),
        migrations.RemoveField(
            model_name='run',
            name='openmbvUpdateTooltip',
        ),
    ]
