# Generated by Django 3.0.1 on 2022-02-25 12:18

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0006_auto_20220225_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='fmatvecTriggered',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='run',
            name='hdf5serieTriggered',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='run',
            name='openmbvTriggered',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='run',
            name='mbsimTriggered',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
