# Generated by Django 3.0 on 2023-11-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0007_add_triggered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='fmatvecTriggered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='run',
            name='hdf5serieTriggered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='run',
            name='mbsimTriggered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='run',
            name='openmbvTriggered',
            field=models.BooleanField(default=False),
        ),
    ]
