# Generated by Django 3.0 on 2023-11-22 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0008_adapt_triggered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('repoName', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('triggered', models.BooleanField(default=False)),
                ('updateOK', models.BooleanField(blank=True, null=True)),
                ('updateOutput', models.TextField()),
                ('updateCommitID', models.CharField(max_length=50)),
                ('updateMsg', models.CharField(max_length=100)),
                ('updateAuthor', models.CharField(max_length=30)),
                ('updateDate', models.DateTimeField(null=True)),
                ('gitURL', models.CharField(max_length=200)),
                ('sourcefileURL', models.CharField(max_length=200)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repos', to='builds.Run')),
            ],
        ),
    ]
