#!/bin/bash

# base variables
BASENAME=$(basename $0)
DIRNAME=$(dirname $0)

if [ "$BASENAME" == "mbsbd" ]; then
  # direct run (not via a link)

  SCRIPTDIR=$(readlink -f $DIRNAME)
  MBSIMENVDIR=$(readlink -f "$SCRIPTDIR"/../../..)
  
  # help
  if [ $# -le 0 ]; then
    echo "This script runs the command provided as first argument in the mbsimenv/build Docker image."
    echo "All other arguments are passed to the command running in Docker."
    echo "If this script is started via a symbolic link to it, then the name of the program to run is"
    echo "the name of link and all arguments are passed."
    echo "Examples:"
    echo "$ <path>/mbsbd make - runs make in the Docker directory corresponding to the current directory."
    echo "$ <path>/mbsbd mbsimxml MBS.mbsx - runs the MBSim XML model MBS.mbsx in the Docker"
    echo "                                           directory corresponding to the current directory."
    echo "..."
    exit 0
  fi
  
  # check docker
  if ! docker version > /dev/null; then
    echo 'Cannot run docker. Please install and enable docker as the current user or'
    echo '(not recommended) run this script as root.'
  fi

  MBSIMENVTAGNAME=${MBSIMENVTAGNAME:-latest}
  
  # convert the absolute path stored in PABS to the corresponding docker path
  function convertPABS {
    PCANO=$(readlink -m $PABS)
    if [ "${PCANO:0:${#MBSIMENVDIR}}" == "$MBSIMENVDIR" ]; then
      PABS=/mbsim-env${PCANO:${#MBSIMENVDIR}}
    else
      echo "ERROR: The path $PABS is not a subdir of $MBSIMENVDIR. This cannot be handled by $BASENAME."
      echo "If you mean a native path in the Docker image prefix this argument with DOCKERDIR:"
      exit 1
    fi
  }
  
  # convert cur dir
  PABS=$PWD; convertPABS; CURDIR=$PABS
  
  #convert args
  ARGS=()
  while [ $# -ge 1 ]; do
    if [ "${1:0:1}" == "/" ]; then
      # convert absolute path
      PABS=$1; convertPABS
      ARGS+=("$PABS")
    elif [ "${1:0:10}" == "DOCKERDIR:" ]; then
      ARGS+=("${1:10}")
    else
      # keep everything else
      ARGS+=("$1")
    fi
    shift
  done
  
  # convert the array ARGS to a single string where " " (space) in each arg is quoted by "\\ "
  # this is only needed for the scl call below which cannot consume multiple arguments
  # if is fixed or scl is not neede instead of "$ARGS_SINGLE" "${ARGS[@]}" should be used
  ARGS_SINGLE=""
  for A in "${ARGS[@]}"; do
    ARGS_SINGLE+=" ${A// /\\ }"
  done
  # run in mbsimenv/build docker image
  docker run -ti --init --entrypoint= --rm \
    --user $(id -u):$(id -g) \
    -v "$MBSIMENVDIR":/mbsim-env \
    -v "$MBSIMENVDIR/.ccache":/mbsim-ccache \
    -v "$MBSIMENVDIR/.home":/tmp/home \
    -e GIT_COMMITTER_NAME=dummy -e GIT_COMMITTER_EMAIL=dummy \
    -e HOME=/tmp/home \
    -e PATH="/mbsim-env/mbsim/examples:/mbsim-env/build/misc:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/3rdparty/local/bin:/mbsim-env/local-docker/bin" \
    -e PKG_CONFIG_PATH="/osupdate/local/lib/pkgconfig:/osupdate/local/lib64/pkgconfig:/3rdparty/local/lib/pkgconfig:/3rdparty/local/lib64/pkgconfig:/mbsim-env/local-docker/lib/pkgconfig:/mbsim-env/local-docker/lib64/pkgconfig" \
    -w "$CURDIR" \
    -e DISPLAY \
    -v ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority \
    --net=host \
    mbsimenv/build:$MBSIMENVTAGNAME \
    scl enable devtoolset-7 "PATH=/usr/lib64/ccache:\$PATH $ARGS_SINGLE"
#    1> >(sed -re "s+/mbsim-env/+$MBSIMENVDIR/+g") 2> >(sed -re "s+/mbsim-env/+$MBSIMENVDIR/+g" > /dev/stderr)

else
  # run via a link

  $DIRNAME/mbsbd $BASENAME "$@"

fi
