#!/bin/bash

SCRIPTDIR=$(readlink -f $(dirname $0))
TAG=latest

# args
ARGS=()
while [ $# -ge 1 ]; do
  # help
  if [ "$1" == "-h" -o "$1" == "--help" ]; then
    echo "This script creates the Docker image mbsimenv/mbsim-env-base from scratch."
    echo "Calling this script it not needed by mbsim-env users or developers since the image is available on Docker-Hub."
    echo "The argument -t <name> or --tag <name> sets the tag of the image to mbsimenv/mbsim-env-base:<name>."
    echo "All other arguments to this script are passed to the docker build command with a default tag-name mbsimenv/mbsim-env-base."
    exit 0
  # tag
  elif [ "$1" == "-t" -o "$1" == "--tag" ]; then
    shift
    TAG=$1
  # others
  else
    ARGS+=("$1")
  fi

  shift
done

sudo docker build -t mbsimenv/mbsim-env-base:$TAG "${ARGS[@]}" "$SCRIPTDIR"
