# Generated by Django 3.0.1 on 2020-05-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CIBranches',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fmatvecBranch', models.CharField(max_length=50)),
                ('hdf5serieBranch', models.CharField(max_length=50)),
                ('openmbvBranch', models.CharField(max_length=50)),
                ('mbsimBranch', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('manualName', models.CharField(max_length=100)),
                ('resultOK', models.BooleanField()),
                ('resultOutput', models.TextField(verbose_name=True)),
                ('manualFile', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=50)),
                ('createDate', models.DateField()),
                ('versionMajor', models.PositiveSmallIntegerField()),
                ('versionMinor', models.PositiveSmallIntegerField()),
                ('releaseFile', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.AddConstraint(
            model_name='release',
            constraint=models.UniqueConstraint(fields=('platform', 'versionMajor', 'versionMinor'), name='unique_releases'),
        ),
        migrations.AddConstraint(
            model_name='cibranches',
            constraint=models.UniqueConstraint(fields=('fmatvecBranch', 'hdf5serieBranch', 'openmbvBranch', 'mbsimBranch'), name='unique_banches'),
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('shortInfo', models.TextField()),
                ('longInfo', models.TextField()),
            ],
        ),
    ]
