# Generated by Django 3.0.1 on 2020-05-29 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIQueue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recTime', models.DateTimeField()),
                ('fmatvecBranch', models.CharField(max_length=50)),
                ('hdf5serieBranch', models.CharField(max_length=50)),
                ('openmbvBranch', models.CharField(max_length=50)),
                ('mbsimBranch', models.CharField(max_length=50)),
            ],
        ),
    ]
