# Generated by Django 3.0.1 on 2020-07-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_nullempty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciqueue',
            name='buildCommitID',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ciqueue',
            name='fmatvecBranch',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ciqueue',
            name='hdf5serieBranch',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ciqueue',
            name='mbsimBranch',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ciqueue',
            name='openmbvBranch',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='release',
            name='releaseDebugFile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='release',
            name='releaseFile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
