# Generated by Django 3.0.1 on 2020-06-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_cibuild'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciqueue',
            name='buildCommitID',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='releaseDebugFile',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='ciqueue',
            name='fmatvecBranch',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ciqueue',
            name='hdf5serieBranch',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ciqueue',
            name='mbsimBranch',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ciqueue',
            name='openmbvBranch',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
