# Generated by Django 3.0.1 on 2020-07-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_nullblank'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBranches',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fmatvecBranch', models.CharField(max_length=50)),
                ('hdf5serieBranch', models.CharField(max_length=50)),
                ('openmbvBranch', models.CharField(max_length=50)),
                ('mbsimBranch', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='cibranches',
            name='unique_banches',
        ),
        migrations.AddConstraint(
            model_name='cibranches',
            constraint=models.UniqueConstraint(fields=('fmatvecBranch', 'hdf5serieBranch', 'openmbvBranch', 'mbsimBranch'), name='unique_ci_banches'),
        ),
        migrations.AddConstraint(
            model_name='dailybranches',
            constraint=models.UniqueConstraint(fields=('fmatvecBranch', 'hdf5serieBranch', 'openmbvBranch', 'mbsimBranch'), name='unique_daily_banches'),
        ),
    ]
