# Generated by Django 3.0.1 on 2022-02-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_info_buildimageid'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='buildwin64ImageID',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
