#!/bin/bash

ARGS=()
while [ $# -ge 1 ]; do
  if [ "${1:0:1}" == "@" ]; then
    while IFS= read -r line
    do
      ARGS+=("$line")
    done < "${1:1}"
  else
    ARGS+=("$1")
  fi
  shift
done

/usr/x86_64-w64-mingw32/bin/qt5/moc.org "${ARGS[@]}"
