# mfmf manage -j in all docker-compose.yml
version: "2"



services:
  base:
    image: mbsimenv/base
    build: baseImage

  build:
    image: mbsimenv/build
    build: buildImage

  run:
    image: mbsimenv/run
    build:
      context: ..
      dockerfile: docker/runImage/Dockerfile

  autobuild-linux64-ci:
    image: mbsimenv/autobuild
    build:
      context: ..
      dockerfile: docker/autoBuildImage/Dockerfile
    entrypoint: ["/mbsim-build/build/docker/autoBuildImage/entrypoint.py", "--buildType", "linux64-ci"]
    volumes:
      - autobuild-mbsim-linux64-ci:/mbsim-env
      - autobuild-report-linux64-ci:/mbsim-report
      - autobuild-ccache:/mbsim-ccache
      - autobuild-state:/mbsim-state
      - autobuild-config:/mbsim-config

  autobuild-linux64-dailydebug:
    image: mbsimenv/autobuild
    build:
      context: ..
      dockerfile: docker/autoBuildImage/Dockerfile
    entrypoint: ["/mbsim-build/build/docker/autoBuildImage/entrypoint.py", "--buildType", "linux64-dailydebug",
                 "--buildDoc", "--valgrindExamples"]
    volumes:
      - autobuild-mbsim-linux64-dailydebug:/mbsim-env
      - autobuild-report-linux64-dailydebug:/mbsim-report
      - autobuild-ccache:/mbsim-ccache
      - autobuild-state:/mbsim-state
      - autobuild-config:/mbsim-config

  autobuild-linux64-dailyrelease:
    image: mbsimenv/autobuild
    build:
      context: ..
      dockerfile: docker/autoBuildImage/Dockerfile
    command: ["--buildType", "linux64-dailyrelease"]
    entrypoint: ["/mbsim-build/build/docker/autoBuildImage/entrypoint.py", "--buildType", "linux64-dailyrelease"]
    volumes:
      - autobuild-mbsim-linux64-dailyrelease:/mbsim-env
      - autobuild-report-linux64-dailyrelease:/mbsim-report
      - autobuild-ccache:/mbsim-ccache
      - autobuild-state:/mbsim-state
      - autobuild-config:/mbsim-config



volumes:
  autobuild-mbsim-linux64-ci:
  autobuild-report-linux64-ci:
  autobuild-mbsim-linux64-dailydebug:
  autobuild-report-linux64-dailydebug:
  autobuild-mbsim-linux64-dailyrelease:
  autobuild-report-linux64-dailyrelease:
  autobuild-state:
  autobuild-config:
  autobuild-ccache:
