# Generated by Django 3.0.1 on 2020-07-04 08:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('builds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exampleName', models.CharField(max_length=200)),
                ('willFail', models.BooleanField()),
                ('runResult', models.IntegerField(choices=[(0, 'Passed'), (1, 'Failed'), (2, 'Timedout')], null=True)),
                ('runOutput', models.TextField(null=True)),
                ('time', models.DurationField(null=True)),
                ('guiTestHdf5serieOK', models.IntegerField(choices=[(0, 'Passed'), (1, 'Failed'), (2, 'Timedout')], null=True)),
                ('guiTestHdf5serieOutput', models.TextField(null=True)),
                ('guiTestOpenmbvOK', models.IntegerField(choices=[(0, 'Passed'), (1, 'Failed'), (2, 'Timedout')], null=True)),
                ('guiTestOpenmbvOutput', models.TextField(null=True)),
                ('guiTestMbsimguiOK', models.IntegerField(choices=[(0, 'Passed'), (1, 'Failed'), (2, 'Timedout')], null=True)),
                ('guiTestMbsimguiOutput', models.TextField(null=True)),
                ('webappHdf5serie', models.BooleanField()),
                ('webappOpenmbv', models.BooleanField()),
                ('webappMbsimgui', models.BooleanField()),
                ('deprecatedNr', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExampleStatic',
            fields=[
                ('exampleName', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('refTime', models.DurationField(null=True)),
                ('update', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Valgrind',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('programType', models.CharField(max_length=50)),
                ('programCmd', models.TextField()),
                ('valgrindCmd', models.TextField()),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valgrinds', to='runexamples.Example')),
            ],
        ),
        migrations.CreateModel(
            name='ValgrindError',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('kind', models.CharField(max_length=100)),
                ('suppressionRawText', models.TextField()),
                ('valgrind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='runexamples.Valgrind', to_field='uuid')),
            ],
        ),
        migrations.CreateModel(
            name='XMLOutput',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=200)),
                ('resultOK', models.BooleanField()),
                ('resultOutput', models.TextField()),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xmlOutputs', to='runexamples.Example')),
            ],
        ),
        migrations.CreateModel(
            name='ValgrindWhatAndStack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nr', models.PositiveSmallIntegerField()),
                ('what', models.CharField(max_length=200)),
                ('valgrindError', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsAndStacks', to='runexamples.ValgrindError', to_field='uuid')),
            ],
        ),
        migrations.CreateModel(
            name='ValgrindFrame',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nr', models.PositiveSmallIntegerField()),
                ('obj', models.CharField(max_length=250)),
                ('fn', models.TextField()),
                ('dir', models.CharField(max_length=250)),
                ('file', models.CharField(max_length=100)),
                ('line', models.PositiveIntegerField(null=True)),
                ('whatAndStack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stacks', to='runexamples.ValgrindWhatAndStack', to_field='uuid')),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('buildType', models.CharField(max_length=50)),
                ('command', models.TextField()),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField(null=True)),
                ('coverageOK', models.BooleanField(null=True)),
                ('coverageRate', models.FloatField(null=True)),
                ('coverageOutput', models.TextField(null=True)),
                ('build_run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examples', to='builds.Run')),
            ],
        ),
        migrations.CreateModel(
            name='ExampleStaticReference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('h5File', models.FileField(max_length=200, null=True, upload_to='')),
                ('h5FileSHA1', models.CharField(max_length=50)),
                ('exampleStatic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='runexamples.ExampleStatic')),
            ],
        ),
        migrations.AddField(
            model_name='example',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='runexamples.Run'),
        ),
        migrations.CreateModel(
            name='CompareResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('h5Filename', models.CharField(max_length=100)),
                ('dataset', models.CharField(max_length=200)),
                ('label', models.CharField(max_length=100)),
                ('result', models.IntegerField(choices=[(0, 'Passed'), (1, 'Failed'), (2, 'Filenotincur'), (3, 'Filenotinref'), (4, 'Datasetnotincur'), (5, 'Datasetnotinref'), (6, 'Labelnotincur'), (7, 'Labelnotinref'), (8, 'Labeldiffer'), (9, 'Labelmissing')])),
                ('h5File', models.FileField(max_length=200, null=True, upload_to='')),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='runexamples.Example')),
            ],
        ),
        migrations.AddConstraint(
            model_name='valgrindwhatandstack',
            constraint=models.UniqueConstraint(fields=('valgrindError', 'nr'), name='unique_orderPerError'),
        ),
        migrations.AddConstraint(
            model_name='valgrindframe',
            constraint=models.UniqueConstraint(fields=('whatAndStack', 'nr'), name='unique_orderPerStack'),
        ),
    ]
