# Generated by Django 3.0.1 on 2020-06-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runexamples', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valgrindframe',
            name='obj',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='valgrindframe',
            name='fn',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='valgrindframe',
            name='dir',
            field=models.CharField(max_length=250),
        ),
    ]
