# Generated by Django 3.0.1 on 2020-06-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runexamples', '0002_valgrindenlargefields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='guiTestHdf5serieOK',
            field=models.IntegerField(choices=[(0, 'Passed'), (1, 'Failed'), (2, 'Timedout')], null=True),
        ),
        migrations.AlterField(
            model_name='example',
            name='guiTestMbsimguiOK',
            field=models.IntegerField(choices=[(0, 'Passed'), (1, 'Failed'), (2, 'Timedout')], null=True),
        ),
        migrations.AlterField(
            model_name='example',
            name='guiTestOpenmbvOK',
            field=models.IntegerField(choices=[(0, 'Passed'), (1, 'Failed'), (2, 'Timedout')], null=True),
        ),
    ]
