# Generated by Django 3.0.1 on 2020-07-07 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0003_nullblank'),
        ('runexamples', '0002_nullempty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compareresult',
            name='h5File',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='example',
            name='deprecatedNr',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='example',
            name='guiTestHdf5serieOK',
            field=models.IntegerField(blank=True, choices=[(0, 'Passed'), (1, 'Failed'), (2, 'Timedout')], null=True),
        ),
        migrations.AlterField(
            model_name='example',
            name='guiTestHdf5serieOutput',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='example',
            name='guiTestMbsimguiOK',
            field=models.IntegerField(blank=True, choices=[(0, 'Passed'), (1, 'Failed'), (2, 'Timedout')], null=True),
        ),
        migrations.AlterField(
            model_name='example',
            name='guiTestMbsimguiOutput',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='example',
            name='guiTestOpenmbvOK',
            field=models.IntegerField(blank=True, choices=[(0, 'Passed'), (1, 'Failed'), (2, 'Timedout')], null=True),
        ),
        migrations.AlterField(
            model_name='example',
            name='guiTestOpenmbvOutput',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='example',
            name='runOutput',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='example',
            name='runResult',
            field=models.IntegerField(blank=True, choices=[(0, 'Passed'), (1, 'Failed'), (2, 'Timedout')], null=True),
        ),
        migrations.AlterField(
            model_name='example',
            name='time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examplestatic',
            name='refTime',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examplestaticreference',
            name='h5File',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='run',
            name='build_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examples', to='builds.Run'),
        ),
        migrations.AlterField(
            model_name='run',
            name='coverageOK',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='coverageOutput',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='run',
            name='coverageRate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='endTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valgrindframe',
            name='line',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
