# Generated by Django 3.0.1 on 2020-06-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runexamples', '0003_guitests'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplestaticreference',
            name='h5FileSHA1',
            field=models.CharField(default='aaaaaaaaaaaaaaa', max_length=50),
            preserve_default=False,
        ),
    ]
