# Generated by Django 3.0.1 on 2021-07-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runexamples', '0005_compreresultrefactoring_incomplete'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='fmatvecLcov',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='run',
            name='hdf5serieLcov',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='run',
            name='mbsimLcov',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='run',
            name='openmbvLcov',
            field=models.TextField(blank=True),
        ),
    ]
