# Generated by Django 3.0.1 on 2021-10-09 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runexamples', '0006_auto_20210711_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='fmatvecLcov',
        ),
        migrations.RemoveField(
            model_name='run',
            name='hdf5serieLcov',
        ),
        migrations.RemoveField(
            model_name='run',
            name='mbsimLcov',
        ),
        migrations.RemoveField(
            model_name='run',
            name='openmbvLcov',
        ),
    ]
