# Generated by Django 3.0.1 on 2022-02-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runexamples', '0007_auto_20211009_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='executor',
            field=models.TextField(default='<span class="MBSIMENV_EXECUTOR_MBSIMENV">MBSim-Env</span>'),
            preserve_default=False,
        ),
    ]
