# Generated by Django 3.0 on 2023-11-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runexamples', '0009_serverqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='coverageFile',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='example',
            name='guiTestHdf5serieOK',
            field=models.IntegerField(blank=True, choices=[(0, 'Passed'), (1, 'Failed'), (2, 'Warning')], null=True),
        ),
        migrations.AlterField(
            model_name='example',
            name='guiTestMbsimguiOK',
            field=models.IntegerField(blank=True, choices=[(0, 'Passed'), (1, 'Failed'), (2, 'Warning')], null=True),
        ),
        migrations.AlterField(
            model_name='example',
            name='guiTestOpenmbvOK',
            field=models.IntegerField(blank=True, choices=[(0, 'Passed'), (1, 'Failed'), (2, 'Warning')], null=True),
        ),
        migrations.AlterField(
            model_name='example',
            name='runResult',
            field=models.IntegerField(blank=True, choices=[(0, 'Passed'), (1, 'Failed'), (2, 'Warning')], null=True),
        ),
    ]
