# Generated by Django 3.0 on 2023-12-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runexamples', '0010_add_coveragefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='sourceDir',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
