version: "2"



services:
  webserver:
    image: mbsimenv/webserver
    build:
      context: ../..
      dockerfile: docker/webServerImage/Dockerfile
    hostname: ${MBSIMENVSERVERNAME}
    environment:
      - MBSIMENVSERVERNAME
    volumes:
      - autobuild-report-linux64-ci:/var/www/html/mbsim/linux64-ci:ro
      - autobuild-report-linux64-dailydebug:/var/www/html/mbsim/linux64-dailydebug:ro
      - autobuild-report-linux64-dailyrelease:/var/www/html/mbsim/linux64-dailyrelease:ro
      - autobuild-state:/var/www/html/mbsim/buildsystemstate:ro
      - autobuild-config:/mfmf/BuildServiceConfig
      - webserver-releases:/var/www/html/mbsim/releases
      - webserver-letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"



volumes:
  autobuild-report-linux64-ci:
  autobuild-report-linux64-dailydebug:
  autobuild-report-linux64-dailyrelease:
  autobuild-state:
  autobuild-config:
  webserver-releases:
  webserver-letsencrypt:
