name: Build MSYS2 Docker Image (Manual)
on:
  workflow_dispatch:
env:
  # get secrets
  mbsimenvsec_dockerhubAccessToken: ${{secrets.dockerhubAccessToken}}
jobs:
  build:
    name: "Bulid MSYS2 Docker Image"
    runs-on: windows-2019
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Docker login"
        run: echo $Env:mbsimenvsec_dockerhubAccessToken | docker login -u fm12 --password-stdin
#      - name: "Docker pull base"
#        run: docker pull mbsimenv/buildmsys2ucrt64base:latest
#      - name: "Docker build base"
#        run: docker build -t mbsimenv/buildmsys2ucrt64base:latest --cache-from mbsimenv/buildmsys2ucrt64base:latest -f docker/buildmsys2ucrt64baseImage/Dockerfile .
#      - name: "Docker push base"
#        run: docker push mbsimenv/buildmsys2ucrt64base:latest
      - name: "Docker pull build"
        run: docker pull mbsimenv/buildmsys2ucrt64:latest
      - name: "Docker build"
        run: docker build -t mbsimenv/buildmsys2ucrt64:latest --cache-from mbsimenv/buildmsys2ucrt64:latest -f docker/buildmsys2ucrt64Image/Dockerfile .
      - name: "Docker push build"
        run: docker push mbsimenv/buildmsys2ucrt64:latest
