name: Get Build Matrix
on:
  workflow_call:
    inputs:
      dailyRun:
        required: true
        type: boolean
      pushSource:
        required: false # only required for dailyRun==False
        type: string
    outputs:
      matrix:
        value: ${{jobs.getBuildMatrix.outputs.matrix}}
    secrets:
      githubAccessToken:
        required: true
      djangoSecretKey:
        required: true
      postgresPassword:
        required: true
      filestoragePassword:
        required: true
      codecovUploadToken_fmatvec:
        required: true
      codecovUploadToken_hdf5serie:
        required: true
      codecovUploadToken_openmbv:
        required: true
      codecovUploadToken_mbsim:
        required: true
env:
  # tagname and servername of remote mbsimenv server
  MBSIMENVTAGNAME: staging
  MBSIMENVSERVERNAME: wwwstaging.mbsim-env.de
  # connect to this server:port for www, database and filestorage
  MBSIMENVWWW: www.mbsim-env.de:10443
  MBSIMENVDATABASE: www.mbsim-env.de:15432
  MBSIMENVFILESTORAGE: www.mbsim-env.de:11122
  # get secrets
  mbsimenvsec_githubAccessToken: ${{secrets.githubAccessToken}}
  mbsimenvsec_djangoSecretKey: ${{secrets.djangoSecretKey}}
  mbsimenvsec_postgresPassword: ${{secrets.postgresPassword}}
  mbsimenvsec_filestoragePassword: ${{secrets.filestoragePassword}}
  mbsimenvsec_codecovUploadToken_fmatvec: ${{secrets.codecovUploadToken_fmatvec}}
  mbsimenvsec_codecovUploadToken_hdf5serie: ${{secrets.codecovUploadToken_hdf5serie}}
  mbsimenvsec_codecovUploadToken_openmbv: ${{secrets.codecovUploadToken_openmbv}}
  mbsimenvsec_codecovUploadToken_mbsim: ${{secrets.codecovUploadToken_mbsim}}
jobs:
  getBuildMatrix:
    name: "............................................................"
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.matrix.outputs.matrix}}
    steps:
      - name: "Get branch combinations from MBSim-Env server"
        id: matrix
        shell: python
        run: |
          import json
          import requests
          import itertools
          # get branch combinations
          if "${{inputs.dailyRun}}"=="true":
            model="DailyBranches"
          else:
            model="CIBranches"
          response=requests.get("https://${{env.MBSIMENVWWW}}/service/db/getbranchcombi/"+model+"/", verify=False)
          branchCombination=response.json()["data"]
          # check repo
          if "${{inputs.dailyRun}}"=="true":
            matrix={"branches": branchCombination,
              "os": [
                {"buildType": "linux64-dailydebug"  , "image": "mbsimenv/build"     ,  "args": ""},
                {"buildType": "linux64-dailyrelease", "image": "mbsimenv/build"     ,  "args": ""},
                {"buildType": "win64-dailyrelease"  , "image": "mbsimenv/buildwin64",  "args": ""},
              ]}
          else:
            # print repo, branch and sha
            repo="${{fromJson(inputs.pushSource).repository}}".split("/")[1]
            branch="${{fromJson(inputs.pushSource).ref_name}}"
            sha=${{fromJson(inputs.pushSource).sha}}
            print("Got action for repo="+repo+" branch="+branch+" sha="+sha)
            # all branch combinations to build
            branches=list(filter(lambda x: x[repo+"Branch"]==branch, branchCombination))
            # if no branch combination is found build this branch with "master" of all other repos
            if len(branches)==0:
              branches=[{"fmatvecBranch": "master", "hdf5serieBranch": "master", "openmbvBranch": "master", "mbsimBranch": "master"}]
              branches[0][repo+"Branch"]=branch+"*"+sha
            else:
              # override repo branch with sha
              for b in branches:
                b[repo+"Branch"]+="*"+sha
            matrix={"branches": branches,
              "os": [
                {"buildType": "linux64-ci", "image": "mbsimenv/build"     , "args": ""},
                {"buildType": "win64-ci"  , "image": "mbsimenv/buildwin64", "args": ""},
              ]}
          # linearize matrix and remove master, linux-dailydebug combination
          matrix=itertools.product(matrix["branches"], matrix["os"])
          matrix=map(lambda x: {"branches": x[0], "os": x[1]}, matrix)
          matrix=filter(lambda x: x["os"]["buildType"]!="linux64-dailydebug" or
                                  x["branches"]["fmatvecBranch"]!="master" or
                                  x["branches"]["hdf5serieBranch"]!="master" or
                                  x["branches"]["openmbvBranch"]!="master" or
                                  x["branches"]["mbsimBranch"]!="master", matrix)
          matrix={"data": list(matrix)}
          # set output
          print("Build matrix:\n"+json.dumps(matrix, indent=2))
          print("::set-output name=matrix::"+json.dumps(matrix))
