name: Build
on:
  workflow_call:
    inputs:
      matrix: # JSON string: {"data":
              #  [{"os": {"buildType": ?, "image": ?, "args": ?},
              #    "branches": {"fmatvecBranch": ?, "hdf5serieBranch": ?, "openmbvBranch": ?, "mbsimBranch": ?, }, }, ...]}
        required: true
        type: string
      uploadArtifactLocalLcov:
        required: true
        type: boolean
    outputs:
      whatToDo:
        value: ${{jobs.build.outputs.whatToDo}}
      buildInfo:
        value: ${{jobs.build.outputs.buildInfo}}
    secrets:
      githubAccessToken:
        required: true
      mbsimenvAccessToken:
        required: true
      djangoSecretKey:
        required: true
      postgresPassword:
        required: true
      filestoragePassword:
        required: true
      codecovUploadToken_fmatvec:
        required: true
      codecovUploadToken_hdf5serie:
        required: true
      codecovUploadToken_openmbv:
        required: true
      codecovUploadToken_mbsim:
        required: true
env:
  # tagname and servername of remote mbsimenv server
  MBSIMENVTAGNAME: latest
  MBSIMENVSERVERNAME: www.mbsim-env.de
  # connect to this server:port for www, database and filestorage
  MBSIMENVWWW: www.mbsim-env.de:443
  MBSIMENVDATABASE: www.mbsim-env.de:5432
  MBSIMENVFILESTORAGE: www.mbsim-env.de:1122
  # get secrets
  mbsimenvsec_githubAccessToken: ${{secrets.githubAccessToken}}
  mbsimenvsec_mbsimenvAccessToken: ${{secrets.mbsimenvAccessToken}}
  mbsimenvsec_djangoSecretKey: ${{secrets.djangoSecretKey}}
  mbsimenvsec_postgresPassword: ${{secrets.postgresPassword}}
  mbsimenvsec_filestoragePassword: ${{secrets.filestoragePassword}}
  mbsimenvsec_codecovUploadToken_fmatvec: ${{secrets.codecovUploadToken_fmatvec}}
  mbsimenvsec_codecovUploadToken_hdf5serie: ${{secrets.codecovUploadToken_hdf5serie}}
  mbsimenvsec_codecovUploadToken_openmbv: ${{secrets.codecovUploadToken_openmbv}}
  mbsimenvsec_codecovUploadToken_mbsim: ${{secrets.codecovUploadToken_mbsim}}
jobs:
  build:
    name: "${{matrix.data.os.buildType}}: ${{matrix.data.branches.fmatvecBranch}} ${{matrix.data.branches.hdf5serieBranch}} ${{matrix.data.branches.openmbvBranch}} ${{matrix.data.branches.mbsimBranch}}"
    runs-on: ubuntu-latest
    outputs:
      whatToDo: ${{steps.whatToDo.outputs.data}}
      buildInfo: ${{steps.buildDetails.outputs.buildInfo}}
    strategy:
      fail-fast: false
      matrix: ${{fromJson(inputs.matrix)}}
    steps:
      - name: "Dump resources"
        run: echo ***df*** && df && echo ***free*** && free && echo ***cpu*** && cat /proc/cpuinfo | grep "model name"
      - name: "Dump build config"
        run: >
          echo -e " buildType       = ${{matrix.data.os.buildType}}
                    image           = ${{matrix.data.os.image}}:${{env.MBSIMENVTAGNAME}}
                    fmatvecBranch   = ${{matrix.data.branches.fmatvecBranch}}
                    hdf5serieBranch = ${{matrix.data.branches.hdf5serieBranch}}
                    openmbvBranch   = ${{matrix.data.branches.openmbvBranch}}
                    mbsimBranch     = ${{matrix.data.branches.mbsimBranch}}
                    args            = ${{matrix.data.os.args}}
                    Triggered by repo = ${{github.repository}}
                                 branch = ${{github.ref_name}}
                                 sha = ${{github.sha}}
                                 event = ${{github.event_name}}" | tr -s ' '
      - name: "Check what to do"
        id: whatToDo
        shell: python
        run: |
          import requests
          import json
          if ${{github.run_attempt}}>1:
            data={
              "skip": False,
              "runID": None,
              "branches": {
                "fmatvec": "${{matrix.data.branches.fmatvecBranch}}",
                "hdf5serie": "${{matrix.data.branches.hdf5serieBranch}}",
                "openmbv": "${{matrix.data.branches.openmbvBranch}}",
                "mbsim": "${{matrix.data.branches.mbsimBranch}}"
              }
            }
          else:
            # get current branches SHA (if not SHA is specified explicitly)
            branches={}
            branches["fmatvec"]="${{matrix.data.branches.fmatvecBranch}}"
            branches["hdf5serie"]="${{matrix.data.branches.hdf5serieBranch}}"
            branches["openmbv"]="${{matrix.data.branches.openmbvBranch}}"
            branches["mbsim"]="${{matrix.data.branches.mbsimBranch}}"
            rs=requests.Session()
            for repo in ["fmatvec", "hdf5serie", "openmbv", "mbsim"]:
              if len(branches[repo].split("*"))>1:
                continue
              response=rs.get("https://api.github.com/repos/mbsim-env/"+repo+"/branches/"+branches[repo],
                              headers={"Authorization": "token ${{secrets.githubAccessToken}}"})
              if response.status_code==200:
                branches[repo]+="*"+response.json()["commit"]["sha"]
              else:
                raise RuntimeError("Failed to get SHA from github:\n"+response.text)
            # check if a new build is done with this
            def getTriggered(repo):
              branchSplit=branches[repo].split("*")
              if len(branchSplit)<3:
                return 0
              return 1 if branchSplit[2]=="T" else 0
            response=requests.get("https://{HOST}/builds/createUniqueRunID/{BT}/GITHUBACTION/{FMATVECSHA}/{HDF5SERIESHA}/{OPENMBVSHA}/{MBSIMSHA}/{FMATVECTRIGGERED}/{HDF5SERIETRIGGERED}/{OPENMBVTRIGGERED}/{MBSIMTRIGGERED}/".\
                                  format(HOST="${{env.MBSIMENVWWW}}", BT="${{matrix.data.os.buildType}}",
                                         FMATVECSHA=branches["fmatvec"].split("*")[1],
                                         HDF5SERIESHA=branches["hdf5serie"].split("*")[1],
                                         OPENMBVSHA=branches["openmbv"].split("*")[1],
                                         MBSIMSHA=branches["mbsim"].split("*")[1],
                                         FMATVECTRIGGERED=getTriggered("fmatvec"),
                                         HDF5SERIETRIGGERED=getTriggered("hdf5serie"),
                                         OPENMBVTRIGGERED=getTriggered("openmbv"),
                                         MBSIMTRIGGERED=getTriggered("mbsim")),
                                  verify=False,
                                  headers={"Authorization": "token ${{secrets.mbsimenvAccessToken}}"})
            skip=True
            runID=None
            if response.status_code==200:
              createUniqueRunID=response.json()
              print("createUniqueRunID:\n"+json.dumps(createUniqueRunID, indent=2))
              runID=createUniqueRunID["runID"]
              if runID is not None:
                skip=False
            else:
              raise RuntimeError("Failed to createUniqueRunID:\n"+response.text)
            data={"skip": skip, "runID": runID, "branches": branches}
          print("jobs.build.steps.whatToDo.outputs.data:\n"+json.dumps(data, indent=2))
          print("::set-output name=data::"+json.dumps(data))
      - name: "Docker: pull image"
        if: ${{!fromJson(steps.whatToDo.outputs.data).skip}}
        run: >
          docker image pull ${{matrix.data.os.image}}:${{env.MBSIMENVTAGNAME}} &&
          mkdir -m 777 -p ${{github.workspace}}/mbsim-env ${{github.workspace}}/mbsim-ccache
      - name: "Create build matrix UUID"
        if: ${{!fromJson(steps.whatToDo.outputs.data).skip}}
        shell: python
        id: matrixUUID
        run: |
          import uuid
          print("jobs.build.steps.matrixUUID.outputs.matrixUUID:\n"+str(uuid.uuid4()))
          print("::set-output name=matrixUUID::"+str(uuid.uuid4()))
      - name: "Cache: ccache"
        if: ${{!fromJson(steps.whatToDo.outputs.data).skip}}
        uses: actions/cache@v2
        with:
          path: ${{github.workspace}}/mbsim-ccache
          key: ccache-${{matrix.data.os.buildType}}--${{steps.matrixUUID.outputs.matrixUUID}}
          restore-keys: |
            ccache-${{matrix.data.os.buildType}}--
      - name: "Cache: fix ccache file permissions"
        if: ${{!fromJson(steps.whatToDo.outputs.data).skip}}
        run: chmod -R 777 ${{github.workspace}}/mbsim-ccache # the docker user id is different than the current user id
      - name: "Docker: run container"
        if: ${{!fromJson(steps.whatToDo.outputs.data).skip}}
        run: >
          docker run
          --init
          --label buildtype=${{matrix.data.os.buildType}}
          --env MBSIMENVDATABASE
          --env MBSIMENVFILESTORAGE
          --env MBSIMENVSERVERNAME
          --env MBSIMENVTAGNAME
          --env MBSIMENVIMAGEID=$(docker image inspect -f "{{.Id}}" ${{matrix.data.os.image}}:${{env.MBSIMENVTAGNAME}})
          --env mbsimenvsec_githubAccessToken
          --env mbsimenvsec_mbsimenvAccessToken
          --env mbsimenvsec_djangoSecretKey
          --env mbsimenvsec_postgresPassword
          --env mbsimenvsec_filestoragePassword
          --env mbsimenvsec_codecovUploadToken_fmatvec
          --env mbsimenvsec_codecovUploadToken_hdf5serie
          --env mbsimenvsec_codecovUploadToken_openmbv
          --env mbsimenvsec_codecovUploadToken_mbsim
          -v ${{github.workspace}}/mbsim-env:/mbsim-env
          -v ${{github.workspace}}/mbsim-ccache:/mbsim-ccache
          ${{matrix.data.os.image}}:${{env.MBSIMENVTAGNAME}}
          --buildType ${{matrix.data.os.buildType}}
          --executor '<a class="MBSIMENV_EXECUTOR_GITHUBACTION" href="https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}/attempts/${{github.run_attempt}}">GitHub Actions</a>'
          -j $(nproc)
          ${{github.run_attempt>1 && '--forceBuild' || ''}}
          --ccacheSize 5
          --fmatvecBranch ${{fromJson(steps.whatToDo.outputs.data).branches.fmatvec}}
          --hdf5serieBranch ${{fromJson(steps.whatToDo.outputs.data).branches.hdf5serie}}
          --openmbvBranch ${{fromJson(steps.whatToDo.outputs.data).branches.openmbv}}
          --mbsimBranch ${{fromJson(steps.whatToDo.outputs.data).branches.mbsim}}
          ${{fromJson(steps.whatToDo.outputs.data).runID && '--buildRunID'}} ${{fromJson(steps.whatToDo.outputs.data).runID}}
          ${{matrix.data.os.args}}
      - name: "Dump link to MBSim-Env server"
        if: ${{always() && !fromJson(steps.whatToDo.outputs.data).skip}}
        id: buildDetails
        shell: python
        run: |
          import json
          try:
            with open("${{github.workspace}}/mbsim-env/local/.buildInfo.json", "r") as f:
              buildInfo=json.load(f)
            print("https://${{env.MBSIMENVSERVERNAME}}/builds/run/"+str(buildInfo["buildRunID"])+"/")
            print("jobs.build.steps.buildDetails.outputs.buildInfo:\n"+json.dumps(buildInfo, indent=2))
            print("::set-output name=buildInfo::"+json.dumps(buildInfo))
          except:
            print("No buildInfo file found")
            print("jobs.build.steps.buildDetails.outputs.buildInfo:\n{}")
            print("::set-output name=buildInfo::{}")
      - name: "Artifact: tar/compress prefix and coverage-files"
        if: ${{always() && inputs.uploadArtifactLocalLcov && !fromJson(steps.whatToDo.outputs.data).skip}}
        run: >
          (cd ${{github.workspace}}/mbsim-env/ && find -name "*.gcda" >  ${{github.workspace}}/local-cov.files) &&
          (cd ${{github.workspace}}/mbsim-env/ && find -name "*.gcno" >> ${{github.workspace}}/local-cov.files) &&
          tar -czf ${{github.workspace}}/local-cov.tar.gz -C ${{github.workspace}}/mbsim-env/
          local/ -T ${{github.workspace}}/local-cov.files;
          rm -f ${{github.workspace}}/local-cov.files
      - name: "Artifact: upload prefix and coverage-files"
        if: ${{always() && inputs.uploadArtifactLocalLcov && !fromJson(steps.whatToDo.outputs.data).skip}}
        uses: actions/upload-artifact@v3
        with:
          name: mbsim-env-local-cov
          retention-days: 1
          path: ${{github.workspace}}/local-cov.tar.gz
      - name: "Dump resources"
        if: ${{always()}}
        run: echo ***df*** && df && echo ***free*** && free && echo ***cpu*** && cat /proc/cpuinfo | grep "model name"
