name: MSYS2 Docker Build (Repo-Dispatch)
on:
  push:
    paths:
      - "docker/buildmsys2ucrt64Image/*"
      - "docker/buildImage/distribute.py"
      - "django/mbsimenv/build.py"
      - "django/mbsimenv/runexamples.py"
      - "django/mbsimenv/mbsimenvSecrets.py"
      - "django/mbsimenv/mbsimenv"
      - "django/mbsimenv/base"
      - "django/mbsimenv/builds"
      - "django/mbsimenv/runexamples"
      - "django/mbsimenv/service"
env:
  # get secrets
  mbsimenvsec_dockerhubAccessToken: ${{secrets.dockerhubAccessToken}}
jobs:
  build:
    name: "msys2-docker-build"
    runs-on: windows-2019
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Docker login"
        run: echo $Env:mbsimenvsec_dockerhubAccessToken | docker login -u fm12 --password-stdin
      - name: "Docker pull base"
        run: docker pull mbsimenv/buildmsys2ucrt64base:latest
      - name: "Docker pull"
        run: docker pull mbsimenv/buildmsys2ucrt64:latest
      - name: "Docker build"
        run: docker build -t mbsimenv/buildmsys2ucrt64:latest --cache-from mbsimenv/buildmsys2ucrt64:latest -f docker/buildmsys2ucrt64Image/Dockerfile .
      - name: "Docker push"
        run: docker push mbsimenv/buildmsys2ucrt64:latest
