name: CI (Repo-Dispatch)
on:
  repository_dispatch:
    types: [ci]
  workflow_dispatch:
    inputs: # data equal to everything needed by mbsim-env-getbuildmatrix.yml from github.event.client_payload
      repository:
        description: "Triggered repo"
        required: true
        default: "mbsim"
        type: choice
        options:
        - "mbsim-env/fmatvec"
        - "mbsim-env/hdf5serie"
        - "mbsim-env/openmbv"
        - "mbsim-env/mbsim"
      ref_name:
        description: "Triggered branch in repo"
        required: true
        default: "master"
        type: string
      sha:
        description: "Triggered sha in repo"
        required: true
        default: ""
        type: string
env:
  # tagname and servername of remote mbsimenv server
  MBSIMENVTAGNAME: latest
  MBSIMENVSERVERNAME: www.mbsim-env.de
  # connect to this server:port for www, database and filestorage
  MBSIMENVWWW: www.mbsim-env.de:443
  MBSIMENVDATABASE: www.mbsim-env.de:5432
  MBSIMENVFILESTORAGE: www.mbsim-env.de:1122
  # get secrets
  mbsimenvsec_githubAccessToken: ${{secrets.githubAccessToken}}
  mbsimenvsec_mbsimenvAccessToken: ${{secrets.mbsimenvAccessToken}}
  mbsimenvsec_djangoSecretKey: ${{secrets.djangoSecretKey}}
  mbsimenvsec_postgresPassword: ${{secrets.postgresPassword}}
  mbsimenvsec_filestoragePassword: ${{secrets.filestoragePassword}}
jobs:



  getBuildMatrix:
    name: Get build matrix
    uses: ./.github/workflows/mbsim-env-getbuildmatrix.yml
    with:
      dailyRun: false
      pushSource: ${{ (github.event_name == 'workflow_dispatch' && toJson(inputs)) || toJson(github.event.client_payload) }}
    secrets:
      githubAccessToken: ${{secrets.githubAccessToken}}
      mbsimenvAccessToken: ${{secrets.mbsimenvAccessToken}}
      djangoSecretKey: ${{secrets.djangoSecretKey}}
      postgresPassword: ${{secrets.postgresPassword}}
      filestoragePassword: ${{secrets.filestoragePassword}}
  buildMatrix:
    name: B&e
    uses: ./.github/workflows/mbsim-env-build.yml
    needs: getBuildMatrix
    with:
      matrix: ${{needs.getBuildMatrix.outputs.matrix}}
      uploadArtifactLocalLcov: false
    secrets:
      githubAccessToken: ${{secrets.githubAccessToken}}
      mbsimenvAccessToken: ${{secrets.mbsimenvAccessToken}}
      djangoSecretKey: ${{secrets.djangoSecretKey}}
      postgresPassword: ${{secrets.postgresPassword}}
      filestoragePassword: ${{secrets.filestoragePassword}}
