name: CI msys2 (Repo-Dispatch)
on:
  push:
jobs:
  build:
    name: "win64-ci-msys2"
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: "Install msys2"
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: UCRT64
          install: >
            dos2unix
            patch
            mingw-w64-ucrt-x86_64-arpack
            mingw-w64-ucrt-x86_64-autotools
            mingw-w64-ucrt-x86_64-boost
            mingw-w64-ucrt-x86_64-cmake
            mingw-w64-ucrt-x86_64-doxygen
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-graphviz
            mingw-w64-ucrt-x86_64-hdf5
            mingw-w64-ucrt-x86_64-octave
            mingw-w64-ucrt-x86_64-openblas
            mingw-w64-ucrt-x86_64-python-numpy
            mingw-w64-ucrt-x86_64-python-sympy
            mingw-w64-ucrt-x86_64-qwt-qt5
            mingw-w64-ucrt-x86_64-soqt
            mingw-w64-ucrt-x86_64-spooles
            mingw-w64-ucrt-x86_64-swig
            mingw-w64-ucrt-x86_64-xalan-c
            mingw-w64-ucrt-x86_64-xerces-c
      - name: "Checkout build repo"
        uses: actions/checkout@v4
      - name: "patch swig"
        run: cd /ucrt64/share/swig/4.1.1 && patch -p2 < $(cygpath -u $GITHUB_WORKSPACE)/msys2ucrt64Build/swig.git.patch
      - name: "Checkout mbsim-env repos"
        run: >
          git clone https://github.com/mbsim-env/fmatvec.git &&
          git clone https://github.com/mbsim-env/hdf5serie.git &&
          git clone https://github.com/mbsim-env/openmbv.git &&
          git clone https://github.com/mbsim-env/mbsim.git
      - name: "Start build.sh"
        run: ./build/msys2ucrt64Build/build.sh
